version: "1"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/src:ro
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
    - ./docker/db/my.cnf:/etc/mysql/my.cnf
    - ./docker/db/mysql_data:/var/lib/mysql
    ports:
      - "53306:3306"
    env_file:
      - ./docker/db/db-variables.env
    platform: linux/amd64
